#!/bin/bash
PS3="选择:"
conf=./user_conf/PAYLOAD

info(){
        echo "PAYLOAD=$1" > $conf
}

num=0
for file in `ls -F ./payloads | grep -v "/"`
do
	clist[$num]="$file"
	((num++))
done

select mode in ${clist[@]}
do
	if [[ $mode == "" ]];then
	echo "错误的选项。"
	else
	info $mode
	break
	fi
done

echo -e "\033[32m操作完成，文件内容：\033[0m\n\033[36m`cat $conf`\033[0m"
