#!/bin/bash
PS3="选择:"
file=./user_conf/PAYLOAD

clist=(
"network_only"
"Win10_LockPicker"
"hid_backdoor"
"stickykey/add"
"stickykey/remove"
"stickykey/trigger"
)

info(){
	echo "PAYLOAD=$1" > $file
}

select mode in ${clist[@]}
do
	#case "$mode" in
   	#"quit")
	#break
        #;;
	#*)
	info $mode
	break
	#break
	#;;
	#esac
done

echo -e "\033[32m操作完成，文件内容：\033[0m\n\033[36m`cat $file`\033[0m"
